# Generated by Django 5.0.4 on 2024-06-21 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('favorites', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavoritestore',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='users.customer'),
        ),
        migrations.AddField(
            model_name='userfavoritestore',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.store'),
        ),
        migrations.AlterUniqueTogether(
            name='userfavoritestore',
            unique_together={('customer', 'store')},
        ),
    ]
