# Generated by Django 5.0.4 on 2024-08-01 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_cat_name', models.CharField(max_length=50, verbose_name='카테고리명')),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_title', models.CharField(max_length=30)),
                ('community_content', models.TextField()),
                ('community_img', models.ImageField(upload_to='community/img')),
                ('community_like', models.IntegerField(default=0)),
                ('community_shotform', models.FileField(blank=True, null=True, upload_to='community/videos')),
                ('community_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('liked_by', models.ManyToManyField(related_name='liked_posts', to='users.customer')),
                ('product', models.ManyToManyField(blank=True, related_name='communities', to='logistics.product')),
                ('selected_products', models.ManyToManyField(blank=True, related_name='selected_communities', to='logistics.product')),
                ('community_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.communitycategory')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_comment_content', models.CharField(max_length=100)),
                ('community_comment_like', models.IntegerField(default=0)),
                ('community_comment_date', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('liked_by', models.ManyToManyField(related_name='liked_comments', to='users.customer')),
            ],
        ),
    ]
